### ISSUE TITLE
DTE and Prisma

### ISSUE THREAD

**Issue by smasala** [gperdomor/nx-tools#408] opened 2021-12-31 11:27 UTC
Any ideas on how to get the client to generate correctly for Distributed Task Execution? https://github.com/nrwl/nx/discussions/8342

**Comment by gperdomor** [comment] 2022-01-02 02:17
Just create a new target in your project.json file to generate the client, something like this:

```json
"prisma-generate": {
    "executor": "@nx-tools/nx-prisma:generate",
    "options": {
        "schema": "apps/api/src/prisma/schema.prisma"
    }
}
```

and then run in your agents:
```
    - NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx affected --target=prisma-generate --parallel
    - npx nx-cloud start-agent
```

That will generate the client in every distributed agent...

**Comment by smasala** [comment] 2022-01-02 09:35
@gperdomor unfortunately, that doesn't work. Tried that already.

**Comment by smasala** [comment] 2022-01-02 09:50
Project config
```
"prisma-generate": {
      "builder": "@nx-tools/nx-prisma:generate",
      "options": {
        "schema": "libs/mysuperlib:prisma/src/prisma/schema.prisma"
      }
    }
```

Lib:
```
> nx run mysuperlib:prisma-generate 
--> Generating Client...
/opt/hostedtoolcache/node/16.13.1/x64/bin/npx prisma generate --schema=libs/mysuperlib/src/prisma/schema.prisma
Environment variables loaded from .env
Prisma schema loaded from libs/mysuperlib

✔ Generated Prisma Client (3.7.0 | library) to ./node_modules/.pnpm/@prisma+client@3.7.0_prisma@3.7.0/node_modules/@prisma/client in 384ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()


———————————————————————————————————————————————

>  NX   SUCCESS  Running target "prisma-generate" succeeded
```

App build
```
TS2305: Module '"node_modules/@prisma/client"' has no exported member 'Prisma'.
  > 5 | import { Prisma } from '@prisma/client';
      |          ^^^^^^
    8 |
```

Turn off DTE globally and all is fine
![image](https://user-images.githubusercontent.com/1477905/147872223-787588c4-afeb-4f6a-9900-ea339c5a476e.png)

**Comment by gperdomor** [comment] 2022-01-02 18:46
can you provide a minimum reproduction repository?

**Comment by smasala** [comment] 2022-01-03 17:44
@gperdomor sure: https://github.com/smasala/nx-dte-prisma/runs/4693791308?check_suite_focus=true

**Comment by smasala** [comment] 2022-01-04 19:53
P.s. can this even work on "affected"? Don't all libraries that use prisma delete and create the same prisma client?

**Comment by smasala** [comment] 2022-01-04 19:56
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-location-of-prisma-client this should do the trick

**Comment by gperdomor** [comment] 2022-01-05 05:44
@smasala I send a [PR](https://github.com/smasala/nx-dte-prisma/pull/2) to your repo to solve the problem 👍🏻

**Comment by smasala** [comment] 2022-01-05 05:49
@gperdomor thanks, workflows seem to be failing and the agents are stuck in a loop 😬

**Comment by gperdomor** [comment] 2022-01-05 06:02
> @gperdomor thanks, workflows seem to be failing and the agents are stuck in a loop 😬

Maybe because permissions??? weird!... anyways, this is the same code on my fork https://github.com/gperdomor/nx-dte-prisma/pulls and it's working fine... I will try to send a new commit to force a new run

**Comment by smasala** [comment] 2022-01-05 06:19
@gperdomor ok cool, I'll try it out on my actual repo and let you. Thanks for you help 😊👍

**Comment by smasala** [comment] 2022-01-05 14:10
@gperdomor excellent, works thanks!

**Comment by gperdomor** [comment] 2022-01-06 04:17
@smasala glad to hear that... I will close this issue :D

**Closed by gperdomor** 2022-01-06 04:17 UTC

**Comment by brandoncollins7** [comment] 2023-07-12 22:16
What fix was made to this guys code? I am having the same issue

**Comment by AlexJWayne** [comment] 2023-08-25 00:19
Yeah, stumbled into this today, too, and I have no idea what I'm doing wrong here.

**Comment by smasala** [comment] 2023-08-28 14:18
@brandoncollins7 @AlexJWayne 
Run this as an extra step inside your agents:
```
    - name: Generate Prisma
      run: NX_CLOUD_DISTRIBUTED_EXECUTION=false pnpm run nx run-many --target=prisma-generate --all --parallel=1
```

**Comment by sourcecodeit** [comment] 2024-08-03 07:40
I have the same issue. An Nx workspace with many apps and 2 of them using Prisma with their own schema.

I added this in both:

```
generator client {
    provider = "prisma-client-js"
    output   = "../generated/client"
}
```
both project.json have:

```
"prisma-generate": {
      "executor": "@nx-tools/nx-prisma:generate",
      "options": {
        "schema": "importer/prisma/schema.prisma"
      }
    },
```

The command:

`npx nx run-many -t prisma-generate`

works, but if I try to build too then it fails:

`npx nx run-many -t prisma-generate build`

```
    kpi-check/src/app/services/kpi.ts:101:33 - error TS2339: Property 'customer' does not exist on type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>'.
       
          99 | 	if (failedSources.length > 0) {
         100 | 		getLogger().info(`Sending alert for ${failedSources.length} failed indicators`)
       > 101 | 		const customer = await prisma.customer.findFirst({
             | 		                              ^
         102 | 			where: {
         103 | 				code: customerCode
         104 | 			},

```

Clearly, running both tasks on a single project works:

```
nx run kpi-check:prisma-generate
nx run kpi-check:build
```

So my problem is not about the Prisma client but it's about the generated Prisma code.

**Comment by brandoncollins7** [comment] 2024-08-03 13:45
I ended up having each project that uses prisma generate it's code into a seperate models library for each project as opposed to the default location. I found that this way it works and my other microservices which might receive a particular model as a result to a service call can also reference that models project and get free type checking that's in sync

**Comment by sourcecodeit** [comment] 2024-08-03 13:56
> I ended up having each project that uses prisma generate it's code into a seperate models library for each project

You mean this?

```
generator client {
    provider = "prisma-client-js"
    output   = "../generated/client"
}
```

I tried and it works locally but it fails in the Github action

**Comment by sourcecodeit** [comment] 2024-08-03 14:16
Ok it seems it fixed with this:

`npx nx affected -t prisma-generate build --prod --parallel=1`

**Comment by brandoncollins7** [comment] 2024-08-03 14:17
then you probably need a build dependsOn prisma-generate

**Comment by sourcecodeit** [comment] 2024-08-03 14:31
> then you probably need a build dependsOn prisma-generate

thanks, that seems it fixes too!
