### ISSUE TITLE
Dockerfile couldn't be found

### ISSUE THREAD

**Issue by ArcanusMagnus** [gperdomor/nx-tools#1158] opened 2024-11-08 10:13 UTC
@nx-tools/nx-container version 6.1.0, nx version 20.0.7

Hello,

After migrating NX and nx-tools to newer version, our target container couldn't find the Dockerfile in any project anymore.

Turned out that we had to specify 

`file": "{projectRoot}/Dockerfile",`

in each project.json. This value was a default previously. 

Is it intended? If not, might be a problem with our configuration, but also a possible bug.

**Comment by gperdomor** [comment] 2024-11-08 12:16
@ArcanusMagnus Hi... It's not intended, the bug is caused by removal of deprecated things in Nx 20... It's fixed in 6.1.1 😄

**Closed** 2024-11-08 13:46 UTC
