### ISSUE TITLE
INPUT_TAGS doesn't support setting multiple tags

### ISSUE THREAD

**Issue by mrfelton** [gperdomor/nx-tools#764] opened 2023-03-20 05:24 UTC
ref nx-container https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/docs/inputs.md

> Note: For list values use a comma-delimited string, like `INPUT_TAGS=user/app:v1,user/app:latest`

This doesn’t appear to work. Following the example there:

`INPUT_TAGS=user/app:v1,user/app:latest nx container api`

The resulting docker build command only has a single tag `--tag api:user-app-latest`

I would expect it to have to tags, like `--tag api:user-app-v1 --tag=api:user-app-latest`

**Comment by gperdomor** [comment] 2024-01-26 13:39
This is a duplicate of https://github.com/gperdomor/nx-tools/issues/356 but in summary, if you want to use metadata and override the tags using environment variables please check this https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/TROUBLESHOOTING.md#inline-execution

**Closed by gperdomor** 2024-01-26 13:39 UTC
